import type {
  Team,
  User,
  ReadinessScore,
  WellnessCheckin,
  AthleteAvailability,
  AcademicRecord,
  Alert,
  TeamEvent,
  StaffNote,
  MatchStat,
  TrainingSession,
  SessionPlanV2,
  WorkloadEntry,
  InjuryRecord,
  AvailabilityHistoryEntry,
} from '@/types/database'

// ---------------------------------------------------------------------------
// Stable IDs for referential integrity across demo data
// ---------------------------------------------------------------------------
export const DEMO_TEAM_ID = 'demo-team-mcmaster-001'

export const DEMO_ATHLETE_IDS = {
  marcus: 'demo-athlete-001',
  priya: 'demo-athlete-002',
  jordan: 'demo-athlete-003',
  sofia: 'demo-athlete-004',
  liam: 'demo-athlete-005',
  amara: 'demo-athlete-006',
  noah: 'demo-athlete-007',
  elena: 'demo-athlete-008',
  devonte: 'demo-athlete-009',
}

export const DEMO_COACH_ID = 'demo-coach-001'

// ---------------------------------------------------------------------------
// Team
// ---------------------------------------------------------------------------
export const DEMO_TEAM: Team = {
  id: DEMO_TEAM_ID,
  name: 'McMaster Marauders',
  sport: 'Soccer',
  league: 'OUA',
  institution: 'McMaster University',
  season_label: '2025–26',
  created_at: '2025-08-01T00:00:00Z',
}

// ---------------------------------------------------------------------------
// Athletes (9)
// ---------------------------------------------------------------------------
export const DEMO_ATHLETES: User[] = [
  {
    id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    full_name: 'Marcus Thompson',
    role: 'athlete',
    jersey_number: 10,
    position: 'Forward',
    year_of_study: '3rd Year',
    avatar_color: '#d4ff5c',
    initials: 'MT',
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.priya,
    team_id: DEMO_TEAM_ID,
    full_name: 'Priya Sharma',
    role: 'athlete',
    jersey_number: 7,
    position: 'Midfielder',
    year_of_study: '2nd Year',
    avatar_color: '#2dd4bf',
    initials: 'PS',
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    full_name: 'Jordan Casey',
    role: 'athlete',
    jersey_number: 1,
    position: 'Goalkeeper',
    year_of_study: '4th Year',
    avatar_color: '#60a5fa',
    initials: 'JC',
    created_at: '2025-08-15T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.sofia,
    team_id: DEMO_TEAM_ID,
    full_name: 'Sofia Reyes',
    role: 'athlete',
    jersey_number: 4,
    position: 'Defender',
    year_of_study: '1st Year',
    avatar_color: '#fb7185',
    initials: 'SR',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.liam,
    team_id: DEMO_TEAM_ID,
    full_name: 'Liam Okafor',
    role: 'athlete',
    jersey_number: 11,
    position: 'Winger',
    year_of_study: '2nd Year',
    avatar_color: '#fbbf24',
    initials: 'LO',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.amara,
    team_id: DEMO_TEAM_ID,
    full_name: 'Amara Diallo',
    role: 'athlete',
    jersey_number: 6,
    position: 'Midfielder',
    year_of_study: '3rd Year',
    avatar_color: '#a78bfa',
    initials: 'AD',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.noah,
    team_id: DEMO_TEAM_ID,
    full_name: 'Noah Bergström',
    role: 'athlete',
    jersey_number: 5,
    position: 'Defender',
    year_of_study: '4th Year',
    avatar_color: '#4ade80',
    initials: 'NB',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.elena,
    team_id: DEMO_TEAM_ID,
    full_name: 'Elena Volkov',
    role: 'athlete',
    jersey_number: 9,
    position: 'Striker',
    year_of_study: '2nd Year',
    avatar_color: '#2dd4bf',
    initials: 'EV',
    created_at: '2025-08-25T00:00:00Z',
  },
  {
    id: DEMO_ATHLETE_IDS.devonte,
    team_id: DEMO_TEAM_ID,
    full_name: 'Devonte Williams',
    role: 'athlete',
    jersey_number: 8,
    position: 'Midfielder',
    year_of_study: '3rd Year',
    avatar_color: '#fb7185',
    initials: 'DW',
    created_at: '2025-08-25T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Coach user
// ---------------------------------------------------------------------------
export const DEMO_COACH: User = {
  id: DEMO_COACH_ID,
  team_id: DEMO_TEAM_ID,
  full_name: 'Coach Sarah Mitchell',
  role: 'coach',
  avatar_color: '#d4ff5c',
  initials: 'SM',
  created_at: '2025-08-01T00:00:00Z',
}

// ---------------------------------------------------------------------------
// Readiness Scores (today's snapshot for each athlete)
// ---------------------------------------------------------------------------
const TODAY = '2026-03-21'

export const DEMO_READINESS_SCORES: ReadinessScore[] = [
  {
    id: 'rs-001',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 82,
    sleep_score: 78,
    combined_score: 80,
    training_load: 14.2,
    hrv: 68,
    resting_hr: 52,
    sleep_hours: 7.5,
    strain: 11.4,
    wearable_source: 'whoop',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-002',
    athlete_id: DEMO_ATHLETE_IDS.priya,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 91,
    sleep_score: 88,
    combined_score: 90,
    training_load: 11.8,
    hrv: 74,
    resting_hr: 48,
    sleep_hours: 8.2,
    strain: 9.1,
    wearable_source: 'garmin',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-003',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 55,
    sleep_score: 60,
    combined_score: 57,
    training_load: 16.5,
    hrv: 44,
    resting_hr: 64,
    sleep_hours: 6.1,
    strain: 15.2,
    wearable_source: 'whoop',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-004',
    athlete_id: DEMO_ATHLETE_IDS.sofia,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 76,
    sleep_score: 72,
    combined_score: 74,
    training_load: 12.0,
    hrv: 61,
    resting_hr: 55,
    sleep_hours: 7.2,
    strain: 10.8,
    wearable_source: 'manual',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-005',
    athlete_id: DEMO_ATHLETE_IDS.liam,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 88,
    sleep_score: 85,
    combined_score: 87,
    training_load: 10.5,
    hrv: 71,
    resting_hr: 50,
    sleep_hours: 8.0,
    strain: 8.4,
    wearable_source: 'whoop',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-006',
    athlete_id: DEMO_ATHLETE_IDS.amara,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 42,
    sleep_score: 50,
    combined_score: 46,
    training_load: 17.8,
    hrv: 38,
    resting_hr: 70,
    sleep_hours: 5.5,
    strain: 16.9,
    wearable_source: 'garmin',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-007',
    athlete_id: DEMO_ATHLETE_IDS.noah,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 79,
    sleep_score: 82,
    combined_score: 80,
    training_load: 13.1,
    hrv: 66,
    resting_hr: 53,
    sleep_hours: 7.8,
    strain: 11.0,
    wearable_source: 'whoop',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-008',
    athlete_id: DEMO_ATHLETE_IDS.elena,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 67,
    sleep_score: 63,
    combined_score: 65,
    training_load: 14.9,
    hrv: 55,
    resting_hr: 58,
    sleep_hours: 6.8,
    strain: 13.2,
    wearable_source: 'manual',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'rs-009',
    athlete_id: DEMO_ATHLETE_IDS.devonte,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    physical_score: 85,
    sleep_score: 80,
    combined_score: 83,
    training_load: 11.2,
    hrv: 69,
    resting_hr: 51,
    sleep_hours: 7.9,
    strain: 9.8,
    wearable_source: 'whoop',
    created_at: `${TODAY}T06:00:00Z`,
  },
]

// ---------------------------------------------------------------------------
// Wellness Check-ins
// ---------------------------------------------------------------------------
export const DEMO_WELLNESS_CHECKINS: WellnessCheckin[] = [
  {
    id: 'wc-001',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    date: TODAY,
    mood_score: 7,
    stress_level: 4,
    energy_level: 7,
    notes: 'Feeling good after yesterday\'s session.',
    mental_score: 72,
    created_at: `${TODAY}T07:00:00Z`,
  },
  {
    id: 'wc-002',
    athlete_id: DEMO_ATHLETE_IDS.priya,
    date: TODAY,
    mood_score: 9,
    stress_level: 2,
    energy_level: 9,
    notes: '',
    mental_score: 88,
    created_at: `${TODAY}T07:05:00Z`,
  },
  {
    id: 'wc-003',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    date: TODAY,
    mood_score: 4,
    stress_level: 8,
    energy_level: 3,
    notes: 'Exam week. Struggling to sleep. Left knee sore.',
    mental_score: 38,
    created_at: `${TODAY}T07:12:00Z`,
  },
  {
    id: 'wc-004',
    athlete_id: DEMO_ATHLETE_IDS.amara,
    date: TODAY,
    mood_score: 3,
    stress_level: 9,
    energy_level: 2,
    notes: 'Feeling burned out. Hard week.',
    mental_score: 28,
    created_at: `${TODAY}T07:20:00Z`,
  },
  {
    id: 'wc-005',
    athlete_id: DEMO_ATHLETE_IDS.liam,
    date: TODAY,
    mood_score: 8,
    stress_level: 3,
    energy_level: 8,
    notes: '',
    mental_score: 82,
    created_at: `${TODAY}T07:30:00Z`,
  },
]

// ---------------------------------------------------------------------------
// Athlete Availability
// ---------------------------------------------------------------------------
export const DEMO_AVAILABILITY: AthleteAvailability[] = [
  {
    id: 'av-001',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-002',
    athlete_id: DEMO_ATHLETE_IDS.priya,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-003',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'limited',
    reason: 'Left knee soreness',
    notes: 'No high-intensity running. Cleared for light training.',
    cleared_by: DEMO_COACH_ID,
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-004',
    athlete_id: DEMO_ATHLETE_IDS.amara,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'out',
    reason: 'Overtraining / Fatigue',
    notes: 'Mandatory rest day. Check in with physio.',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-005',
    athlete_id: DEMO_ATHLETE_IDS.sofia,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-006',
    athlete_id: DEMO_ATHLETE_IDS.liam,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-007',
    athlete_id: DEMO_ATHLETE_IDS.noah,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-008',
    athlete_id: DEMO_ATHLETE_IDS.elena,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'limited',
    reason: 'Mild hamstring tightness',
    notes: 'Monitoring. No sprinting today.',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
  {
    id: 'av-009',
    athlete_id: DEMO_ATHLETE_IDS.devonte,
    team_id: DEMO_TEAM_ID,
    date: TODAY,
    status: 'full',
    reason: '',
    notes: '',
    cleared_by: '',
    created_at: `${TODAY}T06:00:00Z`,
  },
]

// ---------------------------------------------------------------------------
// Academic Records
// ---------------------------------------------------------------------------
export const DEMO_ACADEMIC_RECORDS: AcademicRecord[] = [
  {
    id: 'ac-001',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    gpa: 3.4,
    attendance_pct: 92,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-002',
    athlete_id: DEMO_ATHLETE_IDS.priya,
    team_id: DEMO_TEAM_ID,
    gpa: 3.9,
    attendance_pct: 98,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-003',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    gpa: 2.1,
    attendance_pct: 74,
    eligibility_status: 'review',
    flag_reason: 'Academic standing below eligibility threshold. Referred to academic advisor.',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'ac-004',
    athlete_id: DEMO_ATHLETE_IDS.sofia,
    team_id: DEMO_TEAM_ID,
    gpa: 3.7,
    attendance_pct: 96,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-005',
    athlete_id: DEMO_ATHLETE_IDS.liam,
    team_id: DEMO_TEAM_ID,
    gpa: 3.2,
    attendance_pct: 88,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-006',
    athlete_id: DEMO_ATHLETE_IDS.amara,
    team_id: DEMO_TEAM_ID,
    gpa: 2.8,
    attendance_pct: 81,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-007',
    athlete_id: DEMO_ATHLETE_IDS.noah,
    team_id: DEMO_TEAM_ID,
    gpa: 3.5,
    attendance_pct: 90,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-008',
    athlete_id: DEMO_ATHLETE_IDS.elena,
    team_id: DEMO_TEAM_ID,
    gpa: 3.6,
    attendance_pct: 93,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'ac-009',
    athlete_id: DEMO_ATHLETE_IDS.devonte,
    team_id: DEMO_TEAM_ID,
    gpa: 3.0,
    attendance_pct: 85,
    eligibility_status: 'ok',
    flag_reason: '',
    updated_at: '2026-02-15T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Alerts (3)
// ---------------------------------------------------------------------------
export const DEMO_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    team_id: DEMO_TEAM_ID,
    athlete_id: DEMO_ATHLETE_IDS.amara,
    alert_type: 'low_readiness',
    severity: 'critical',
    message: 'Amara Diallo: Readiness score 46 — 3-day declining trend. Consider mandatory rest.',
    is_read: false,
    created_at: `${TODAY}T06:30:00Z`,
  },
  {
    id: 'alert-002',
    team_id: DEMO_TEAM_ID,
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    alert_type: 'academic_flag',
    severity: 'warning',
    message: 'Jordan Casey: Academic standing flagged — below eligibility threshold. Academic advisor referral recommended.',
    is_read: false,
    created_at: `${TODAY}T07:00:00Z`,
  },
  {
    id: 'alert-003',
    team_id: DEMO_TEAM_ID,
    athlete_id: DEMO_ATHLETE_IDS.elena,
    alert_type: 'injury_flag',
    severity: 'warning',
    message: 'Elena Volkov: Hamstring tightness reported for second consecutive day. Physio assessment recommended.',
    is_read: true,
    created_at: '2026-03-20T09:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Staff Notes
// ---------------------------------------------------------------------------
export const DEMO_STAFF_NOTES: StaffNote[] = [
  {
    id: 'sn-001',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    author_id: DEMO_COACH_ID,
    author_role: 'coach',
    note_text: 'Jordan mentioned exam pressure is affecting sleep. Spoke briefly after practice — will follow up with academic support office.',
    tags: ['academic', 'mental-health', 'sleep'],
    source: 'manual',
    is_private: true,
    created_at: '2026-03-18T16:00:00Z',
  },
  {
    id: 'sn-002',
    athlete_id: DEMO_ATHLETE_IDS.amara,
    team_id: DEMO_TEAM_ID,
    author_id: DEMO_COACH_ID,
    author_role: 'coach',
    note_text: 'Amara appeared withdrawn in warm-up today. Low energy, minimally communicative. Flagging for wellness check-in conversation.',
    tags: ['wellbeing', 'fatigue'],
    source: 'manual',
    is_private: true,
    created_at: '2026-03-20T17:30:00Z',
  },
  {
    id: 'sn-003',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    author_id: DEMO_COACH_ID,
    author_role: 'coach',
    note_text: 'Marcus had an excellent training session — sharp on set pieces, good leadership with younger players.',
    tags: ['performance', 'leadership'],
    source: 'manual',
    is_private: false,
    created_at: '2026-03-19T17:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Upcoming Events (next 5)
// ---------------------------------------------------------------------------
export const DEMO_UPCOMING_EVENTS: TeamEvent[] = [
  {
    id: 'ev-001',
    team_id: DEMO_TEAM_ID,
    title: 'Morning Training',
    event_type: 'training',
    event_date: '2026-03-22',
    start_time: '07:30',
    duration_mins: 90,
    location: 'Ron Joyce Stadium — Pitch A',
    notes: 'Tactical focus: high press. Full squad expected.',
    created_by: DEMO_COACH_ID,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'ev-002',
    team_id: DEMO_TEAM_ID,
    title: 'OUA League Match vs. Western Mustangs',
    event_type: 'match',
    event_date: '2026-03-26',
    start_time: '14:00',
    duration_mins: 110,
    location: 'TD Stadium, London ON',
    notes: 'Away match. Bus departs campus 09:00.',
    created_by: DEMO_COACH_ID,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'ev-003',
    team_id: DEMO_TEAM_ID,
    title: 'Recovery & Film Session',
    event_type: 'film',
    event_date: '2026-03-27',
    start_time: '10:00',
    duration_mins: 60,
    location: 'Team Room 204',
    notes: 'Post-match film review. Attendance mandatory.',
    created_by: DEMO_COACH_ID,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'ev-004',
    team_id: DEMO_TEAM_ID,
    title: 'Strength & Conditioning Block',
    event_type: 'training',
    event_date: '2026-03-28',
    start_time: '08:00',
    duration_mins: 75,
    location: 'Ivor Wynne Athletic Centre',
    notes: 'Lower body focus. Bring your training log.',
    created_by: DEMO_COACH_ID,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'ev-005',
    team_id: DEMO_TEAM_ID,
    title: 'Home Match vs. Queens Golden Gaels',
    event_type: 'match',
    event_date: '2026-04-02',
    start_time: '13:00',
    duration_mins: 110,
    location: 'Ron Joyce Stadium — Main Pitch',
    notes: 'Home fixture. Pre-match activation 12:00.',
    created_by: DEMO_COACH_ID,
    created_at: '2026-03-15T00:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Training Sessions (recent)
// ---------------------------------------------------------------------------
export const DEMO_TRAINING_SESSIONS: TrainingSession[] = [
  {
    id: 'ts-001',
    team_id: DEMO_TEAM_ID,
    title: 'High-Intensity Interval Block',
    session_type: 'cardio',
    duration_mins: 75,
    avg_rpe: 8.2,
    intensity: 'high',
    notes: 'Sprint repeats + possession drills. High load day.',
    created_by: DEMO_COACH_ID,
    session_date: '2026-03-20',
    created_at: '2026-03-20T09:00:00Z',
  },
  {
    id: 'ts-002',
    team_id: DEMO_TEAM_ID,
    title: 'Tactical Shape & Set Pieces',
    session_type: 'tactical',
    duration_mins: 90,
    avg_rpe: 6.0,
    intensity: 'moderate',
    notes: 'Defensive shape vs. 4-2-3-1. Corner routines.',
    created_by: DEMO_COACH_ID,
    session_date: '2026-03-19',
    created_at: '2026-03-19T09:00:00Z',
  },
  {
    id: 'ts-003',
    team_id: DEMO_TEAM_ID,
    title: 'Recovery Activation',
    session_type: 'recovery',
    duration_mins: 45,
    avg_rpe: 3.5,
    intensity: 'low',
    notes: 'Foam rolling, light jog, mobility. Post travel.',
    created_by: DEMO_COACH_ID,
    session_date: '2026-03-18',
    created_at: '2026-03-18T09:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Match Stats (recent)
// ---------------------------------------------------------------------------
export const DEMO_MATCH_STATS: MatchStat[] = [
  {
    id: 'ms-001',
    athlete_id: DEMO_ATHLETE_IDS.marcus,
    team_id: DEMO_TEAM_ID,
    match_date: '2026-03-15',
    opponent: 'Laurier Golden Hawks',
    minutes_played: 90,
    goals: 2,
    assists: 1,
    rating: 9.0,
    notes: 'Outstanding performance. Key to 3-1 win.',
    created_at: '2026-03-15T20:00:00Z',
  },
  {
    id: 'ms-002',
    athlete_id: DEMO_ATHLETE_IDS.priya,
    team_id: DEMO_TEAM_ID,
    match_date: '2026-03-15',
    opponent: 'Laurier Golden Hawks',
    minutes_played: 90,
    goals: 0,
    assists: 2,
    rating: 8.2,
    notes: 'Controlled tempo well. Strong pressing engine.',
    created_at: '2026-03-15T20:00:00Z',
  },
  {
    id: 'ms-003',
    athlete_id: DEMO_ATHLETE_IDS.jordan,
    team_id: DEMO_TEAM_ID,
    match_date: '2026-03-15',
    opponent: 'Laurier Golden Hawks',
    minutes_played: 90,
    goals: 0,
    assists: 0,
    rating: 7.5,
    notes: '4 saves. Solid distribution.',
    created_at: '2026-03-15T20:00:00Z',
  },
]

// ---------------------------------------------------------------------------
// Derived summary statistics for dashboard
// ---------------------------------------------------------------------------
export const DEMO_TEAM_READINESS = 71 // team average combined_score

export const DEMO_AVAILABILITY_SUMMARY = {
  full: 7,
  limited: 2,
  out: 1,
  total: 9,
}

export const DEMO_RECENT_ACTIVITY = [
  {
    id: 'act-001',
    type: 'alert',
    title: 'Critical alert: Amara Diallo — low readiness',
    description: 'Readiness score 46 — 3-day declining trend.',
    timestamp: `${TODAY}T06:30:00Z`,
    severity: 'critical' as const,
  },
  {
    id: 'act-002',
    type: 'checkin',
    title: 'Jordan Casey submitted wellness check-in',
    description: 'Mood 4/10 · Stress 8/10 · Energy 3/10',
    timestamp: `${TODAY}T07:12:00Z`,
    severity: 'warning' as const,
  },
  {
    id: 'act-003',
    type: 'training',
    title: 'Training session logged',
    description: 'High-Intensity Interval Block · avg RPE 8.2',
    timestamp: '2026-03-20T18:00:00Z',
    severity: 'info' as const,
  },
]

// ---------------------------------------------------------------------------
// Session Plans V2
// ---------------------------------------------------------------------------
export const DEMO_SESSION_PLANS: SessionPlanV2[] = [
  {
    id: 'spv2-001',
    title: 'Pre-Match Activation — Western Away',
    date: '2026-03-25',
    startTime: '10:00',
    venue: 'Ron Joyce Stadium — Pitch A',
    sessionType: 'pre-match',
    status: 'planned',
    blocks: [
      {
        id: 'blk-001',
        type: 'warm-up',
        name: 'Dynamic Warm-Up',
        durationMins: 15,
        intensity: 'low',
        drills: ['Dynamic stretching circuit', 'Light jog with direction changes', 'Rondo 4v2'],
        coachNotes: 'Keep it light — legs must be fresh for travel tomorrow.',
      },
      {
        id: 'blk-002',
        type: 'technical',
        name: 'One-Touch Passing Patterns',
        durationMins: 20,
        intensity: 'low',
        drills: ['Triangle passing (first touch)', 'Long switch passes', 'Combination play patterns'],
        coachNotes: 'Pair players by position. Focus on quality not quantity.',
      },
      {
        id: 'blk-003',
        type: 'set-pieces',
        name: 'Set Piece Rehearsal',
        durationMins: 15,
        intensity: 'low',
        drills: ['Corner routines A, B, C and short', 'Defensive set piece walkthrough', 'Free kick A (near post)'],
        coachNotes: 'Run each routine twice. No contact — walkthrough only.',
      },
      {
        id: 'blk-004',
        type: 'cool-down',
        name: 'Cool-Down & Team Talk',
        durationMins: 10,
        intensity: 'low',
        drills: ['Light jog and shake-out', 'Static stretching', 'Team huddle — match day instructions'],
        coachNotes: 'End on a high. Confirm travel time and bus meeting point.',
      },
    ],
  },
  {
    id: 'spv2-002',
    title: 'Tactical Press Patterns',
    date: '2026-03-22',
    startTime: '09:00',
    venue: 'Ron Joyce Stadium — Pitch A',
    sessionType: 'tactical',
    status: 'planned',
    blocks: [
      {
        id: 'blk-010',
        type: 'warm-up',
        name: 'Activation Warm-Up',
        durationMins: 15,
        intensity: 'low',
        drills: ['Rondo 4v2', 'Passing patterns with movement', 'Dynamic mobility'],
        coachNotes: 'High energy from the start — set the tone.',
      },
      {
        id: 'blk-011',
        type: 'tactical',
        name: 'Pressing Triggers',
        durationMins: 25,
        intensity: 'medium',
        drills: ['Shadow pressing walkthrough', '5v5+2 press and counter', 'Defensive shape transition drill'],
        coachNotes: 'Watch Jordan and Elena during transition sprints — limit exposure.',
      },
      {
        id: 'blk-012',
        type: 'physical',
        name: 'High-Intensity Conditioning',
        durationMins: 20,
        intensity: 'high',
        drills: ['Sprint intervals (4×40m)', 'High-intensity 8v8 press scenario', 'Repeated sprint tolerance'],
        coachNotes: 'Jordan on limited today — modified running loads only. Elena keep to 70% sprint intensity.',
      },
      {
        id: 'blk-013',
        type: 'set-pieces',
        name: 'Corner Routines',
        durationMins: 15,
        intensity: 'low',
        drills: ['Attacking corners (A and B variant)', 'Short corner combo', 'Defensive corner clearing drill'],
        coachNotes: 'Liam delivering all corners today. Review video clip from Laurier match.',
      },
      {
        id: 'blk-014',
        type: 'cool-down',
        name: 'Cool-Down',
        durationMins: 10,
        intensity: 'low',
        drills: ['5-minute jog', 'Team static stretch', 'Session debrief'],
        coachNotes: 'Collect RPE data before athletes leave.',
      },
    ],
  },
]

// ---------------------------------------------------------------------------
// Workload Entries (7 days × 9 athletes)
// ---------------------------------------------------------------------------
function makeLoad(durationMins: number, rpe: number): number {
  const modifiers: Record<number, number> = { 1: 0.6, 2: 0.8, 3: 1.0, 4: 1.2, 5: 1.4 }
  return Math.round(durationMins * (modifiers[rpe] ?? 1.0))
}

const WORKLOAD_DATES = [
  '2026-03-20', '2026-03-19', '2026-03-18', '2026-03-17',
  '2026-03-16', '2026-03-15', '2026-03-14',
]

// Baseline loads per athlete (different to create interesting patterns)
// Amara: high (overtraining story), Jordan: elevated, rest: normal range
const ATHLETE_WORKLOAD_PROFILES: Record<string, { durationBase: number; rpeBase: number }> = {
  [DEMO_ATHLETE_IDS.marcus]: { durationBase: 75, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.priya]: { durationBase: 75, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.jordan]: { durationBase: 70, rpeBase: 4 }, // elevated
  [DEMO_ATHLETE_IDS.sofia]: { durationBase: 72, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.liam]: { durationBase: 75, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.amara]: { durationBase: 90, rpeBase: 5 }, // overtraining
  [DEMO_ATHLETE_IDS.noah]: { durationBase: 72, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.elena]: { durationBase: 68, rpeBase: 3 },
  [DEMO_ATHLETE_IDS.devonte]: { durationBase: 75, rpeBase: 3 },
}

let _wlId = 1
export const DEMO_WORKLOAD_ENTRIES: WorkloadEntry[] = WORKLOAD_DATES.flatMap((date) =>
  Object.entries(ATHLETE_WORKLOAD_PROFILES).map(([athleteId, profile]) => {
    const duration = profile.durationBase + Math.floor(Math.random() * 10 - 5)
    const rpe = Math.max(1, Math.min(5, profile.rpeBase + Math.floor(Math.random() * 3 - 1)))
    return {
      id: `wl-${String(_wlId++).padStart(3, '0')}`,
      athleteId,
      date,
      durationMins: duration,
      rpe,
      load: makeLoad(duration, rpe),
      sessionType: 'tactical',
    } satisfies WorkloadEntry
  })
)

// ---------------------------------------------------------------------------
// Injury Records
// ---------------------------------------------------------------------------
export const DEMO_INJURY_RECORDS: InjuryRecord[] = [
  {
    id: 'inj-001',
    athleteId: DEMO_ATHLETE_IDS.jordan,
    injuryType: 'soft-tissue',
    bodyLocation: 'Left Knee',
    severity: 2,
    dateOfOnset: '2026-03-18',
    mechanism: 'training',
    description: 'Left knee soreness following high-intensity session. Possible patellar tendon irritation.',
    expectedReturn: '2026-04-01',
    treatmentPlan: 'Rest, ice, compression for 48h. Physio assessment day 3. Graduated return from day 5.',
    rtpStage: 1,
    stageEnteredAt: { 1: '2026-03-21T00:00:00Z' },
  },
  {
    id: 'inj-002',
    athleteId: DEMO_ATHLETE_IDS.elena,
    injuryType: 'soft-tissue',
    bodyLocation: 'Right Hamstring',
    severity: 1,
    dateOfOnset: '2026-03-20',
    mechanism: 'training',
    description: 'Mild hamstring tightness reported by athlete. No mechanism of injury identified.',
    expectedReturn: '2026-03-27',
    treatmentPlan: 'Monitoring. No sprinting until symptom-free. Physio review before return to full.',
    rtpStage: 0,
    stageEnteredAt: {},
  },
  {
    id: 'inj-003',
    athleteId: DEMO_ATHLETE_IDS.amara,
    injuryType: 'overuse',
    bodyLocation: 'General',
    severity: 1,
    dateOfOnset: '2026-03-21',
    mechanism: 'training',
    description: 'Fatigue and overtraining syndrome. Athlete reported feeling burned out.',
    expectedReturn: '2026-03-26',
    treatmentPlan: 'Mandatory rest. No training for 48h minimum. Review wellness scores daily.',
    rtpStage: 0,
    stageEnteredAt: {},
  },
]

// ---------------------------------------------------------------------------
// Availability History (last 7 days for flagged athletes)
// ---------------------------------------------------------------------------
export const DEMO_AVAILABILITY_HISTORY: AvailabilityHistoryEntry[] = [
  // Jordan — escalating knee concern
  {
    id: 'avh-001',
    athleteId: DEMO_ATHLETE_IDS.jordan,
    date: '2026-03-15',
    status: 'full',
    restriction: '',
    reason: '',
    reasonCategory: '',
    decisionMaker: 'coaching staff',
    expectedReturn: '',
  },
  {
    id: 'avh-002',
    athleteId: DEMO_ATHLETE_IDS.jordan,
    date: '2026-03-18',
    status: 'limited',
    restriction: 'No high-intensity running',
    reason: 'Left knee soreness reported post-session',
    reasonCategory: 'Injury',
    decisionMaker: 'physio',
    expectedReturn: '2026-04-01',
  },
  {
    id: 'avh-003',
    athleteId: DEMO_ATHLETE_IDS.jordan,
    date: '2026-03-21',
    status: 'limited',
    restriction: 'Light training only — no contact, no sprinting',
    reason: 'Ongoing left knee — physio assessment confirmed patellar irritation',
    reasonCategory: 'Injury',
    decisionMaker: 'physio',
    expectedReturn: '2026-04-01',
  },
  // Elena — hamstring tightness
  {
    id: 'avh-004',
    athleteId: DEMO_ATHLETE_IDS.elena,
    date: '2026-03-19',
    status: 'full',
    restriction: '',
    reason: '',
    reasonCategory: '',
    decisionMaker: 'coaching staff',
    expectedReturn: '',
  },
  {
    id: 'avh-005',
    athleteId: DEMO_ATHLETE_IDS.elena,
    date: '2026-03-20',
    status: 'limited',
    restriction: 'No sprinting',
    reason: 'Mild hamstring tightness — athlete-reported',
    reasonCategory: 'Injury',
    decisionMaker: 'athlete reported',
    expectedReturn: '2026-03-27',
  },
  // Amara — overtraining
  {
    id: 'avh-006',
    athleteId: DEMO_ATHLETE_IDS.amara,
    date: '2026-03-19',
    status: 'full',
    restriction: '',
    reason: '',
    reasonCategory: '',
    decisionMaker: 'coaching staff',
    expectedReturn: '',
  },
  {
    id: 'avh-007',
    athleteId: DEMO_ATHLETE_IDS.amara,
    date: '2026-03-20',
    status: 'limited',
    restriction: 'Reduced intensity — no conditioning blocks',
    reason: 'Accumulated load concern flagged by system',
    reasonCategory: 'Injury',
    decisionMaker: 'coaching staff',
    expectedReturn: '2026-03-23',
  },
  {
    id: 'avh-008',
    athleteId: DEMO_ATHLETE_IDS.amara,
    date: '2026-03-21',
    status: 'out',
    restriction: 'Full rest',
    reason: 'Fatigue/overtraining — mandatory rest day. Coach decision.',
    reasonCategory: 'Injury',
    decisionMaker: 'coaching staff',
    expectedReturn: '2026-03-26',
  },
]

// ---------------------------------------------------------------------------
// Top-level DEMO_DATA export
// ---------------------------------------------------------------------------
export const DEMO_DATA = {
  team: DEMO_TEAM,
  coach: DEMO_COACH,
  athletes: DEMO_ATHLETES,
  readinessScores: DEMO_READINESS_SCORES,
  wellnessCheckins: DEMO_WELLNESS_CHECKINS,
  availability: DEMO_AVAILABILITY,
  academicRecords: DEMO_ACADEMIC_RECORDS,
  alerts: DEMO_ALERTS,
  staffNotes: DEMO_STAFF_NOTES,
  upcomingEvents: DEMO_UPCOMING_EVENTS,
  trainingSessions: DEMO_TRAINING_SESSIONS,
  matchStats: DEMO_MATCH_STATS,
  teamReadiness: DEMO_TEAM_READINESS,
  availabilitySummary: DEMO_AVAILABILITY_SUMMARY,
  recentActivity: DEMO_RECENT_ACTIVITY,
  sessionPlans: DEMO_SESSION_PLANS,
  workloadEntries: DEMO_WORKLOAD_ENTRIES,
  injuryRecords: DEMO_INJURY_RECORDS,
  availabilityHistory: DEMO_AVAILABILITY_HISTORY,
}
